name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: exit 0
  delivery:
    name: Delivery
    needs:
      - ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Your delivery here"
